### ISSUE TITLE
OpenGL option

### ISSUE THREAD

**Issue by legluondunet** [libretro/mednafen-psx-libretro#1]
Hello,

I obtain a huge difference quality graphic for PS1 emulation between retroarch and PCSXR:

Moto Racer 1 on Retroarch Mednafen core
![capture du 2015-02-07 13 59 30](https://cloud.githubusercontent.com/assets/325405/6114678/19a3ead0-b0a0-11e4-91d8-acf34fad24ab.png)

![capture du 2015-02-07 13 59 14](https://cloud.githubusercontent.com/assets/325405/6114687/263fc82c-b0a0-11e4-94cb-01366f1fa934.png)

Moto Racer 1 on PCSXR
![capture du 2015-02-07 13 28 45](https://cloud.githubusercontent.com/assets/325405/6114690/2a33151a-b0a0-11e4-91b9-7b818a9c9562.png)

![capture du 2015-02-07 13 28 34](https://cloud.githubusercontent.com/assets/325405/6114693/2e5a1e18-b0a0-11e4-84da-ba16b2891a84.png)

Is there an OpenGL option to render better graphics? Is it planned?

**Comment by fr500** [comment]
It's not poor graphic quality or anythig, it's a software renderer rendering at the native res, that's it.
Mednafen is not a plugin based emulator so it's not like you can just bake the plugin or anything. I've heard there might be 2x internal res in the future (software rendered)

**Comment by legluondunet** [comment]
Retroarch lacks support for opengl PS1 rendering, MEDNAFEN is software rendering only and PCSXRearmed give opengl plugin only to armed devices...it's for me an issue.

**Comment by twinaphex** [comment]
> PCSXRearmed give opengl plugin only to armed devices..

Wrong, it's not an OpenGL plugin at all, it is software rendered.

**Comment by legluondunet** [comment]
NEON is not an opengl plugin?

**Comment by twinaphex** [comment]
No. Take it up with Ryphecha if you want resolution increases.

**Comment by mudlord** [comment]
Or one could port the NEON code to SSE...But then that takes someone with a knowledge of ARM asm and SSE intrinsics.

**Comment by PowaBanga** [comment]
so, if I understand, for the moment, the psx game graphics are not improvable for the moment in retroarch ?

**Comment by hizzlekizzle** [comment]
@PowaBanga This issue is super-old. You can totally increase the internal res and do PGXP texture correction, etc.

**Comment by PowaBanga** [comment]
Maybe because english is not my maternal langage, but I look for some tutorial or information about that, and I do not find or understand how to do that. Can you help me ?

**Comment by hizzlekizzle** [comment]
Sure, but this isn't the place to do it. Register on the forums at:
https://forums.libretro.com
and I/we will get you fixed up :)
