### ISSUE TITLE
Gray textures in Crash Bandicoot 3

### ISSUE THREAD

**Issue by marespiaut** [libretro/mednafen-psx-libretro#2]
Hello,

I'm experiencing some graphical glitches with the latest revision of this core with Crash Bandicoot 3 and other games. Mostly about wrong colors, here are some screenshots.
![retroarch-0218-181457](https://cloud.githubusercontent.com/assets/7140682/6252783/096efee4-b79d-11e4-8dc5-0bd06f879586.png)
Gray trexture [Crash Bandicoot 3]
![retroarch-0218-181614](https://cloud.githubusercontent.com/assets/7140682/6252799/1da4fc88-b79d-11e4-86d2-baabf3b613b0.png)
Green pixels in the background [Crash Bandicoot 3]
![retroarch-0218-182040](https://cloud.githubusercontent.com/assets/7140682/6252858/7e990dae-b79d-11e4-812c-b810555d1a0d.png)
Colors seems wrong here. Foreground is too green-y and there's a very sharp cut between the background fog and the scene [Silent Hill]

**Comment by marespiaut** [comment]
One last screenshot. Spyro the dragon.
Gray-ish landspace, blood waterfalls and black dragon statue.
![retroarch-0218-192420lol](https://cloud.githubusercontent.com/assets/7140682/6253739/fe5d3514-b7a3-11e4-9c14-b1d1c9f2e2ac.png)

**Comment by twinaphex** [comment]
Are you sure this is not beetle-psx instead?

**Comment by marespiaut** [comment]
It's from the beetle-psx indeed, I'm sorry for the mistake.

**Comment by twinaphex** [comment]
Can you re-open this in the beetle repo then? Closing this.
