### ISSUE TITLE
Discworld Noir gives a Blackscreen, with sound

### ISSUE THREAD

**Issue by RagnaStrife** [libretro/mednafen-psx-libretro#4]
I load the .CCD with .IMG and .SUB, but doesn't work right. Did I do something wrong?
I think it doesn't load subchannel data and applies antipiracy. Or is it a bug?

**Comment by fr500** [comment]
Test the games in mednafen standalone, if it works then it may be an issue with libretro, otherwise it's a mednafen issue.

**Comment by RagnaStrife** [comment]
It works if you force it to US video-mode and disable autodetect. Something weird considering it is a genuine PAL game.

**Comment by RagnaStrife** [comment]
Okay, I talked to the main development team but they don't want to fix that ever it seems.
At least I hope someone here exposes video-mode settings for retroarch as a somewhat clunky solution.

**Comment by RagnaStrife** [comment]
Now I am kinda embarrased, but it seems my disc rip had been corrupted somehow.
Sorry. Close this.
