### ISSUE TITLE
Ridge Racer Type 4 Black Screen on Menu (Regression)

### ISSUE THREAD

**Issue by Awakened0** [libretro/mednafen-psx-libretro#9]
cubatilles on the forums describes the issue in detail: http://libretro.com/forums/showthread.php?t=3616&p=26440&viewfull=1#post26440

He mentions similar problems in the Moto Racer games, but R4 is the only one I have on hand and confirmed.

**Comment by fr500** [comment]
can you bisect?

**Comment by Awakened0** [comment]
I don't have git or anything to compile installed anymore. I tried to google how to bisect once and couldn't figure it out anyways :(

**Comment by twinaphex** [comment]
Just tested here, works fine. 

I think what fr500 needs to do is just remove the repo on the buildbot and git clone it again, I had to forcepush some patches a few days ago. That might have resolved the issue with games that use interlaced resolutions.

**Comment by Awakened0** [comment]
Thanks twinaphex. I just tested Tobal 2, which is interlaced even during gameplay, and it black screens as well. So it must be the interlacing.

**Comment by twinaphex** [comment]
Yeah I noticed it first in Tobal 2. Should be resolved now in the latest source.

**Comment by Awakened0** [comment]
Confirmed fixed on the latest buildbot core. Thanks again!
